# Generated by Django 4.0.7 on 2023-07-22 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=50)),
                ('middelName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('registrationDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='class_subject',
            name='teacherId',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='middelName',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='sex',
        ),
        migrations.AddField(
            model_name='family',
            name='family_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.family_type'),
        ),
        migrations.AddField(
            model_name='student',
            name='family_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.family'),
        ),
        migrations.AlterField(
            model_name='class_subject',
            name='classRoomId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.class_room'),
        ),
        migrations.AlterField(
            model_name='class_subject',
            name='subjectId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject'),
        ),
        migrations.AlterField(
            model_name='teacher_subject',
            name='subjectId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.student'),
        ),
        migrations.AlterField(
            model_name='teacher_subject',
            name='teacherId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.teacher'),
        ),
        migrations.DeleteModel(
            name='Student_Family',
        ),
        migrations.AddField(
            model_name='employees',
            name='Job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.job'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='employees_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.employees'),
        ),
    ]
