# Generated by Django 4.0.7 on 2023-07-22 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_employees_job_remove_class_subject_teacherid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_subject',
            name='subjectId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject'),
        ),
    ]
